// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLDestroyer is an autogenerated mock type for the URLDestroyer type
type URLDestroyer struct {
	mock.Mock
}

// DestroyURL provides a mock function with given fields: alias
func (_m *URLDestroyer) DestroyURL(alias string) error {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for DestroyURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLDestroyer creates a new instance of URLDestroyer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLDestroyer(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLDestroyer {
	mock := &URLDestroyer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
